#!/bin/bash

set -e

mkdir -p build

BUILD_CMD="emcc -pthread -Impv-build/build_libs/include \
    -lembind -lopenal -lopfs.js -sWASMFS -sENVIRONMENT=web,worker \
    -sMODULARIZE -sEXPORTED_RUNTIME_METHODS=['PThread'] -sEXPORT_NAME='libmpvLoader' \
    -sINITIAL_MEMORY=2GB -sMEMORY64 -sPROXY_TO_PTHREAD -sOFFSCREENCANVAS_SUPPORT \
    -o build/libmpv.js libmpv.cpp"

find mpv-build/build_libs/lib/*.a -type f -exec $BUILD_CMD {} +

cp build/libmpv.js react-app/src
cp build/libmpv.js react-app/public/static/js
cp build/libmpv.wasm react-app/public/static/js
cp build/interface.d.ts react-app/src/types