#!/bin/sh

set -e

if ! [ -d "node_modules" ]; then
    npm install
fi

if ! [ -d "demo/node_modules" ]; then
    npm --prefix demo install
fi

if ! [ -d "demo-vanilla/node_modules" ]; then
    npm --prefix demo-vanilla install
fi

if ! [ -f "node_modules/typescript/bin/tsc" ]; then
    echo "tsc command not found"
    exit 1
fi

COUNT=$(find shaders -type f | wc -l)

if [ -z $BUILD_PATH ]; then
    USER_OPTION="-e ID=$(id -u):$(id -g)"
fi

if [ -z $DOCKER_BUILD ]; then
    if [ "$COUNT" -eq 1 ]; then
        scripts/dl_a4k_shaders
    fi
    
    scripts/rebuild
else
    docker pull brianhvo02/em_mpv:latest

    if [ "$COUNT" -eq 1 ]; then
        docker run --rm -v .:/src/app -w /src/app $USER_OPTION brianhvo02/em_mpv:latest scripts/dl_a4k_shaders
    fi

    docker run --rm -v .:/src/app -w /src/app $USER_OPTION brianhvo02/em_mpv:latest scripts/rebuild
fi