#!/bin/bash

BUILD_CMD="emcc -pthread -Impv-build/build_libs/include --emit-tsd interface.d.ts \
    -lembind -lopenal -lopfs.js -sENVIRONMENT=web,worker \
    -sWASMFS -sFORCE_FILESYSTEM -sMODULARIZE -sEXPORTED_RUNTIME_METHODS=['FS','PThread'] -sEXPORT_NAME='libmpvLoader' \
    -sINITIAL_MEMORY=1024MB -sPTHREAD_POOL_SIZE=16 -sPROXY_TO_PTHREAD=1 -sOFFSCREENCANVAS_SUPPORT=1 \
    -o build/libmpv.js src/libmpv.cpp"

find mpv-build/build_libs/lib/*.a -type f -exec $BUILD_CMD {} +

cp build/libmpv.js react-app/src
cp build/libmpv.js react-app/public/static/js
cp build/libmpv.wasm react-app/public/static/js
cp build/interface.d.ts react-app/src/types