#!/bin/sh

set -e

npm ln

if ! [ -d "demo/node_modules/libmpv-wasm" ]; then
    cd demo
    npm ln libmpv-wasm
fi

if ! [ -d "demo-vanilla/node_modules/libmpv-wasm" ]; then
    cd ../demo-vanilla
    npm ln libmpv-wasm
fi