#!/bin/sh
set -e

./scripts/clean
./scripts/configure
./scripts/build_wasm "$@"
install build_wasm/libmpv.js build_wasm/libmpv.wasm demo/public/static/js
install build_wasm/libmpv.data demo/public
install build_wasm/libmpv.js src

mkdir -p demo-vanilla/dist
install build_wasm/libmpv.js build_wasm/libmpv.wasm build_wasm/libmpv.data demo-vanilla/dist