#!/bin/sh
set -e

apt-get update
apt-get install pkg-config
./scripts/clean
./scripts/configure
./scripts/build_wasm "$@"
install build/libmpv.js build/libmpv.wasm demo/public/static/js
install build/libmpv.data demo/public